<table border="0" cellpadding="0" cellspacing="0" width="100%" bgcolor="#f2f2f2" style="direction:ltr;min-width:320px;text-align:center;color:#292c2e;font-family:-apple-system,BlinkMacSystemFont,Helvetica,Arial,sans-serif">
  <tbody>
    <tr>
      <td bgcolor="#7000e3" style="padding:0;height:0" height="0">
        <div style="background:#7000e3;height:0;max-height:0;overflow:visible">
          <div style="background:#7000e3;height:140px;width:100%"></div>
        </div>
      </td>
    </tr>
    <tr>
      <td bgcolor="#7000e3" style="padding:20px 0;color:#fff">
        <img src="$site_logo" width="170" style="vertical-align:top;font-size:28px;color:#fff">
      </td>
    </tr>
    <tr>
      <td style="padding:0 20px;text-align:center">
        <span style="display:inline-block;vertical-align:top;width:100%;max-width:640px;text-align:left">
          <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width:640px;min-width:320px;margin:0 auto;min-height:460px">
            <tbody>
              <tr>
                <td>
                  <table border="0" cellpadding="0" cellspacing="0" width="100%">
                    <tbody>
                      <tr>
                        <td style="text-align:center;color:#333844;font-size:16px">
                          <table bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0" width="100%">
                            <tbody>
                              <tr></tr>
                              <tr>
                                <td style="padding:0 20px;text-align:center">
                                  <span style="display:inline-block;vertical-align:top;width:100%;max-width:640px;text-align:left">
                                    <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width:640px;min-width:320px;margin:0 auto">
                                      <tbody>
                                        <tr>
                                          <td>
                                            <table border="0" cellpadding="0" cellspacing="0" width="100%">
                                              <tbody>
                                                <tr>
                                                  <td style="text-align:center;color:#333844;font-size:16px">
                                                    <table bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0" width="100%">
                                                      <tbody>
                                                        <tr>
                                                          <td style="padding:8% 5% 0;text-align:center">
                                                            <span style="display:inline-block;vertical-align:top">
                                                              <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width:480px;margin:0 auto">
                                                                <tbody>
                                                                  <tr>
                                                                    <td align="center">
                                                                      <span class="m_2711121925253516390section-title" style="font-size:22px;line-height:26px;color:#000"> $site_name </span>
                                                                    </td>
                                                                  </tr>
                                                                </tbody>
                                                              </table>
                                                            </span>
                                                          </td>
                                                        </tr>
                                                        <tr>
                                                          <td style="padding:2% 5% 3%;text-align:center">
                                                            <span style="font-size:16px;line-height:22px;color:#7f7f7f;display:inline-block;vertical-align:top;max-width:470px"> {lang}1015{/lang} $cp_title {lang}1016{/lang} </span>
                                                          </td>
                                                        </tr>
                                                        <tr>
                                                          <td style="padding:0 0 8%;text-align:center">
                                                            <a href="$site_open" style="display:inline-block;padding:13px 30px;background:#17d417;text-decoration:none;border-radius:8px;color:#fff;font-weight:600;font-size:16px;text-align:center"> {lang}379{/lang} $site_name </a>
                                                          </td>
                                                        </tr>
                                                      </tbody>
                                                    </table>
                                                  </td>
                                                </tr>
                                              </tbody>
                                            </table>
                                          </td>
                                        </tr>
                                      </tbody>
                                    </table>
                                  </span>
                                </td>
                              </tr>
                            </tbody>
                          </table>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </td>
              </tr>
            </tbody>
          </table>
        </span>
      </td>
    </tr>
  </tbody>
</table>