<?php
global $adminUrl;
  if($sm['admin_ajax'] == false){
    header('Location:'.$sm['config']['site_url'].'index.php?page=admin');
  }
?>
<script>
  aurl = 'dating';
  currentMenu = 'dating';
  currentMenuCollapse = ''; 
</script>
<!-- SECTION CONTENT -->
<div class="container-fluid page__container" id="postContainer"
style="padding-top:25px;min-height: 800px "> <div class="card-group"
id="globalResult" > <div class="card card-body text-center"> <div
class="d-flex flex-row align-items-center"> <div class="card-header__title
m-0">Total Dating Post Created</div> <div class="text-amount ml-auto
font16"><?= selectC('dating',''); ?></div> </div> </div> </div>




  <div class="card card-form  flex-column flex-sm-row divHidden" data-selected-data style="display: none">
      <div class="card-form__body card-body-form-group flex">
          <div class="row">
              <div class="col-sm-12">
                  <div class="form-group">
                      <label for="filter_name">Selected <strong data-selected-data-total></strong> reels</label>                    
                  </div>
                  <div class="avatar-group" data-checkedData style="position: absolute;top: -7px;left: 180px">


                  </div>
              </div>                                                 
          </div>
      </div>

      <div class="dropdown">
          <button class="btn bg-white border-left border-top border-top-sm-0 rounded-top-0 rounded-top-sm rounded-left-sm-0" data-toggle="dropdown" data-caret="false" style="border-radius:0px;background: #fff;width: 100%;height: 100%">
             <i class="material-icons icon-30pt" style="color: #000">more_horiz</i>
           </button> 
          <div class="dropdown-menu dropdown-menu-right">
              <a class="dropdown-item" href="javascript:;" onclick="adminBulkAction('approve','reel');" style="font-size: 13px;">
                Approve <span data-selected-data-total></span> reel objects
              </a>
             
              <div class="dropdown-divider"></div>                            
              <a class="dropdown-item" href="javascript:;" onclick="adminBulkAction('delete','reel');" style="font-size: 13px;color: #b50000">
                Delete <span data-selected-data-total></span> reel objects
              </a>                                                 
          </div>
      </div>      
  </div>

  <div class="card card-form">
      <div class="row no-gutters">
          <div class="col-lg-12 col-md-12 col-sm-12 card-form__body" style="min-height: 700px">              
              <div class="table-responsive border-bottom" data-search data-toggle="lists" data-lists-values='["js-lists-values-employee-name"]' style="min-height: 700px" data-table="result">   


                  <table class="table mb-0 thead-border-top-0" style="">
                      <thead>
                          <tr style="background: #fff">
                              <th style="width: 220px;">Description</th>
                              <th style="width: 80px;">Place</th>
                              <th style="width: 110px;">When</th>      
                              <th style="width: 80px;">Budget</th>                           
                              <th style="width: 60px;">Status</th>                            
                              <th style="width: 120px;" id="userCol">User</th>
                              <th style="width: 24px;"></th>
                          </tr>
                      </thead>

                      <tbody class="list" id="dataTable" style="overflow-y: scroll">
                      </tbody>
                  </table>
              </div>
 
              <div class="card-footer text-center">
                <span class="text-muted">Showing </span>
                <span data-current-view></span>
                <span class="text-muted">of </span>
                <span data-current-total-users></span> 
                <span class="text-muted">results</span>
                <a href="#results" data-nextPage-search>
                  <i class="material-icons icon-muted float-right">arrow_forward</i>
                </a>
                <a href="#results" data-backPage-search style="display: none">

                  <i class="material-icons icon-muted float-left" >arrow_backward</i>
                </a>
              </div> 

          </div>                    
      </div>
  </div>    

</div>


<script>
    var viewer;
    var dataPerPage = 50;
    var viewedData = 0;
    var lastPageSearch = 0;
    var search = {};
    var searchData = [];
    var checkedData = [];    
    search['action'] = 'search_date';

    $('[data-sfpost]').each(function(){
        var current = $(this).attr('data-sfpost');
        search[current] = $(this).val();
    });


    //next result page
     $('[data-nextPage-search]').click(function(e){
    
      $('#customCheckAll').prop("checked",false);         
        if(searchData.length > viewedData){
            $('#dataTable').html('');
            var maxResult = viewedData+dataPerPage;

            lastPageSearch = dataPerPage;
            if(searchData.length <= maxResult ){
                maxResult = searchData.length;
                lastPageSearch = maxResult;
            }                    
            for (i = viewedData; i < maxResult; i++) {
              viewedData++;
              $('#dataTable').append(searchData[i]);
              

              
            }
            $('[data-current-view]').text(viewedData);  
            $('[data-backPage-search]').fadeIn(); 
            viewer = new slimLightbox();
            checkIfChecked();  
            tableDropdownEffect();               
        }                
     });  


     //back page
     $('[data-backPage-search]').click(function(e){
        
        $('#dataTable').html('');
        $('#customCheckAll').prop("checked",false);
        var firstBack = dataPerPage*2;
        viewedData = viewedData-firstBack;
        console.log(viewedData);
        if(viewedData <= 0){
            $('[data-backPage-search]').hide();
            viewedData = 0;
        } 
        var maxResult = viewedData+dataPerPage;
        if(searchData.length <= maxResult ){
            maxResult = searchData.length;
        }                                
        for (i = viewedData; i < maxResult; i++) {
          viewedData++;
          $('#dataTable').append(searchData[i]);
        }
        $('[data-current-view]').text(viewedData); 
        viewer = new slimLightbox();
        checkIfChecked();  
        tableDropdownEffect();                               
     });  
       

    //load data
    function loadDataDate(){
      $('#dataTable').css('opacity','0.5');
      
      $.ajax({
        url: request_source()+'/admin.php', 
        data: search,  
        type: "post",
        dataType: 'JSON',        
        success: function(response) {
            $('#searchresultUserIcon').hide();
            $('#searchreelByUserAction').hide();
            $('#searchreelByUserActionDiv').hide();  
            $('#searchreelByIdClose').hide();
            $('#searchreelByIdUpload').hide();

            $('#dataTable').html('');
            $('#dataTable').css('opacity','1');
            $('[data-search]').show();
            $('[data-selected-data]').hide();
            $('#customCheckAll').prop("checked",false);

            if(response['searchUserId'] != ''){
              console.log(response['searchUserPhoto']);
              $('#searchreelByUserPhoto').attr('src',response['searchUserPhoto']);
              $('#searchreelByIdName').html(response['searchUserName']);
              $('#searchresultUserIcon').show();
              $('#searchreelByUserAction').show();
              $('#searchreelByUserActionDiv').show();
              $('#searchreelByIdClose').show();
              $('#searchreelByIdUpload').show();
              $('[data-current-reel-user]').attr('data-current-reel-user',response['searchUserId']);
              var onclick = 'adminUploadReel('+response['searchUserId']+','+response['searchGender']+',"'+response['searchUserPhoto']+'")';
              $('#searchreelByIdUpload').attr('onclick',onclick);              
            }

            setTimeout(function(){
              checkedData = [];
            },1500);
            searchData = response['data'];

            for (i = 0; i < dataPerPage; i++) {
              viewedData++; 
              $('#dataTable').append(response['data'][i]);
            }
            $('#totalResult').text(response.total);

            if(response['total'] < 49){
              viewedData = response['total'];
            }
            var image = $('[data-reel-i=0]').attr('data-reel-src');
            showReelAdmin(image);          
            if(response['total'] == 0){
               $('[data-table="result"]').hide();
            }
            viewer = new slimLightbox();
            $('#searching').hide();
            $('#searchComplete').show();
            $('[data-current-total-users]').text(response.total);
            $('[data-current-view]').text(viewedData);

            tableDropdownEffect();                        
        },
      });
    }

    //loaddata
    loadDataDate();

    function deleteDateRequest(id){
      $('[data-date-request='+id+']').remove();
      $.ajax({ 
        data:  {
          action: 'deleteDateRequest',
          id: id
        },
        url: request_source()+'/api.php', 
        type:  'POST',
        success: function(response){
            
        }
      });       
    }
</script>


