<?php
  if($sm['admin_ajax'] == false){
    header('Location:'.$sm['config']['site_url'].'index.php?page=admin&p=users');
  }
?>
<script>
  aurl = 'revieworders';
  currentMenu = 'all-users';
  currentMenuCollapse = 'revieworders';  
</script>
<?php 
$currentTime = time()-300;

$days = 86400 * 7;
$days = time() - $days;
$date1 = date('m/d/Y', $days);
$date2 = date('m/d/Y', time());
?>



<!-- SECTION CONTENT -->
<div class="container-fluid page__container" style="padding-top:25px;min-height: 800px ">

  <div class="card card-form  flex-column flex-sm-row divHidden" data-search-result style="display: none;height: 60px">
      <div class="card-form__body card-body-form-group flex">
          <div class="row">
              <div class="col-sm-12">
                  <div class="form-group">
                      <label for="filter_name"><i class="material-icons mr-3">search</i> Search result <span id="totalResult"></span> orders for review</label>                    
                  </div>
              </div>                                                 
          </div>
      </div>
      <div class="card-form__body pt-3 flex">
          <div class="row">
              <div class="col-sm-12">
                  <div class="form-group">
                      <input id="filter_name" type="text" data-sfdata="search" class="form-control" placeholder="Search by order id">                    
                  </div>
              </div>                                                 
          </div>
      </div>      
  </div>  



  <div class="card card-form">
      <div class="row no-gutters">
          <div class="col-lg-12 card-form__body">
              <div class="table-responsive border-bottom" data-search data-toggle="lists" data-lists-values='["js-lists-values-employee-name"]' style="min-height: 100px">   
                  <table class="table mb-0 thead-border-top-0" >
                      <thead>
                          <tr style="background: #fff">
                              <th style="width: 200px;">User / Order ID</th>                              
                              <th style="width: 200px;">Action</th>                            
                              <th style="width: 180px;">Gateway</th>                              
                              <th style="width: 220px;">Proof</th> 
                              <th style="width: 120px;">Proof Image</th>
                              <th style="width: 120px;">Date</th>                                        
                              <th></th>
                          </tr>
                      </thead>
                      <tbody class="list" id="dataTable" style="height: 400px;overflow-y: scroll">
                      </tbody>
                  </table>
              </div>

              <div class="card-footer text-center">
                <span class="text-muted">Showing </span>
                <span data-current-view></span>
                <span class="text-muted">of </span>
                <span data-current-total-users></span> 
                <span class="text-muted">results</span>
                <a href="#results" data-nextPage-search>
                  <i class="material-icons icon-muted float-right">arrow_forward</i>
                </a>
                <a href="#results" data-backPage-search style="display: none">
                  <i class="material-icons icon-muted float-left" >arrow_backward</i>
                </a>
              </div> 

          </div>         
      </div>
  </div>    

</div>


<script>
    var dataPerPage = 10;
    var viewedData = 0;
    var lastPageSearch = 0;
    var search = {};
    var searchData = [];
    var checkedData = [];    
    search['action'] = 'search_orders_pending';
    search['search'] = '';
    setTimeout(function(){

    //load data
    function loadData(){
      $.ajax({
        url: request_source()+'/admin.php', 
        data: search,  
        type: "post",
        dataType: 'JSON',        
        success: function(response) {
            $('[data-search]').show();
            searchData = response['data'];
            for (i = 0; i < dataPerPage; i++) {
              viewedData++; 
              $('#dataTable').append(response['data'][i]);
            }
            $('#totalResult').text(response.total);

            $('[data-search-result]').show();
            $('[data-current-total-users]').text(response.total);
            $('[data-current-view]').text(response.total);
        },
      });
    }

    loadData();

    $('[data-sfdata]').keyup(delay(function (e) {
        var current = $(this).attr('data-sfdata');
        search[current] = $(this).val();
        $('#dataTable').html('');
        loadData();
    }, 200));

    //next result page
     $('[data-nextPage-search]').click(function(e){
    
      $('#customCheckAll').prop("checked",false);         
        if(searchData.length > viewedData){
            $('#dataTable').html('');
            var maxResult = viewedData+dataPerPage;

            lastPageSearch = dataPerPage;
            if(searchData.length <= maxResult ){
                maxResult = searchData.length;
                lastPageSearch = maxResult;
            }                    
            for (i = viewedData; i < maxResult; i++) {
              viewedData++;
              $('#dataTable').append(searchData[i]);
            }
            $('[data-current-view]').text(viewedData);  
            $('[data-backPage-search]').fadeIn(); 

            checkIfChecked();                 
        }                
     });  


     //back page
     $('[data-backPage-search]').click(function(e){
        
        $('#dataTable').html('');
        $('#customCheckAll').prop("checked",false);
        var firstBack = dataPerPage*2;
        viewedData = viewedData-firstBack;
        console.log(viewedData);
        if(viewedData <= 0){
            $('[data-backPage-search]').hide();
            viewedData = 0;
        } 
        var maxResult = viewedData+dataPerPage;
        if(searchData.length <= maxResult ){
            maxResult = searchData.length;
        }                                
        for (i = viewedData; i < maxResult; i++) {
          viewedData++;
          $('#dataTable').append(searchData[i]);
        }
        $('[data-current-view]').text(viewedData);
        checkIfChecked();                                  
     });  

  },10);
           
</script>